Crud/Models/ErrorViewModel.cs
using System;

namespace Crud.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Crud/ViewModels/HtmlHelperExtensionMethods.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Html;

namespace Crud.ViewModels
{
    public static class HtmlHelperExtensions
    {
        public const string HttpMethodOverrideFormName = "X-HTTP-Method-Override";
    
        public static IHtmlContent HttpMethodOverride(
            this IHtmlHelper helper,
            System.Net.Http.HttpMethod method, 
            string name = HttpMethodOverrideFormName)
        {
            return helper.Raw($"<input type=\"hidden\" name=\"{name}\" value=\"{method}\" />");
        }
    }    
}

Crud/ViewModels/Widgets/CreateViewModel.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Crud.ViewModels.Widgets
{
    public class CreateViewModel
    {
        public string Name { get; set; }
        public decimal Weight { get; set; }
        public string Manufacturer { get; set; }

        public IList<SelectListItem> Manufacturers =
            new List<SelectListItem>
            {
                new("One", "One"),
                new("Two", "Two"),
                new("Three", "Three"),
            };
    }
}

Crud/ViewModels/Widgets/EditViewModel.cs
namespace Crud.ViewModels.Widgets
{
    public class EditViewModel : CreateViewModel
    {
        // database identifier
        public int Id { get; set; }
    }
}

Crud/ViewModels/Widgets/IndexViewModel.cs
using System;
using System.Collections;
using System.Collections.Generic;

namespace Crud.ViewModels.Widgets
{
    public class IndexViewModel
    {
        public IEnumerable<WidgetModel> Results { get; set; }
            = Array.Empty<WidgetModel>();
    }

    public class WidgetModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Manufacturer { get; set; }
        public decimal Weight { get; set; }
    }
}

Crud/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Crud.Models;

namespace Crud.Controllers
{
    [Route("")]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        [HttpGet, Route("")]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet, Route("privacy")]
        public IActionResult Privacy()
        {
            return View();
        }

        [HttpGet, Route("error")]
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }
    }
}

Crud/Controllers/WidgetsController.cs
using System.Linq;
using System.Security.Cryptography;
using Crud.ViewModels.Widgets;
using Microsoft.AspNetCore.Mvc;

namespace Crud.Controllers
{
    [Route("[controller]")]
    public class WidgetsController : Controller
    {
        // GET
        public IActionResult Index()
        {
            // notification messages, implement them any way you want
            if (TempData.TryGetValue("Message", out var message)) {
                ViewBag.Message = message;
            }

            var indexViewModel = new IndexViewModel
            {
                Results = Enumerable.Range(1, 10)
                    .Select(i => new WidgetModel {
                        Id = i,
                        Name = $"Widget #{i}",
                        Manufacturer = "One",
                        Weight = RandomNumberGenerator.GetInt32(1, 20)
                    }).ToList()
            };
                
            return View(indexViewModel);
        }

        // widget/1
        [HttpGet, Route("{id}")]
        public IActionResult Show(int id)
        {
            // we would call the database
            return View("Show", new EditViewModel { Id = id });
        }

        [HttpGet, Route("new")]
        public IActionResult New()
        {
            // call the database for additional viewmodel data
            return View("New", new CreateViewModel());
        }
        
        // POST /widgets
        [HttpPost, Route("")]
        public IActionResult Create(CreateViewModel input)
        {
            if (ModelState.IsValid)
            {
                // save to database
                // redirect to display page
                return RedirectToAction("Show", new { id = 1 });
            }

            // return view with model-state errors
            // don't forget to hydrate additional viewmodel info
            return View("New", input);
        }

        [HttpGet, Route("{id}/edit")]
        public IActionResult Edit(int id)
        {
            // always call the database for data
            
            return View("Edit", new EditViewModel { Id = id });
        }
        
        [HttpPut, Route("{id}")]
        public IActionResult Update(int id, EditViewModel input)
        {
            if (ModelState.IsValid)
            {
                // save to database
                // redirect to display page
                return RedirectToAction("Show", new { id = input.Id });
            }

            // return view with model-state errors
            // don't forget to hydrate additional viewmodel info
            return View("Edit", input);
        }

        [HttpDelete, Route("{id}")]
        public IActionResult Delete(int id)
        {
            TempData["Message"] = $"Deleted Widget #{id}!";
            return RedirectToAction("Index");
        }
    }
}

Crud/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Crud/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Crud</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Crud</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Widgets" asp-action="Index">Widgets</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2021 - Crud - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Crud/Views/Widgets/Edit.cshtml
@using Crud.ViewModels
@using System.Net.Http
@model Crud.ViewModels.Widgets.EditViewModel

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Widgets > Edit @Model.Id</h2>

<form method="post"
      asp-controller="Widgets"
      asp-action="Update"
      asp-route-id="@Model.Id">
    
    <input type="hidden" asp-for="Id" />
    
    @await Html.PartialAsync("_Edit", Model)
    
    @Html.HttpMethodOverride(HttpMethod.Put)
</form>

Crud/Views/Widgets/Index.cshtml
@using System.Security.Cryptography
@using Crud.ViewModels
@using System.Net.Http
@model Crud.ViewModels.Widgets.IndexViewModel


<h1>Widgets</h1>

<p>
    These widgets are randomly generated on index.
    This is meant to illustrate a common patterns
    building data driven applications utilizing viewmodels.
</p>

<div class="row mb-3">
    <div class="col-12 text-right">
        <a class="btn btn-primary" asp-action="New">New</a>
    </div>
</div>

@await Html.PartialAsync("_Notifications")

<div class="row">
    <div class="col-12">
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>Name</th>
                <th>Weight</th>
                <th>Manufacturer</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            @for (int i = 1; i < 11; i++)
            {
                <tr>
                    <td>Widget #@i</td>
                    <td>@RandomNumberGenerator.GetInt32(1, 100)</td>
                    <td>One</td>
                    <td>
                        <a class="btn btn-secondary" asp-action="Edit" asp-route-id="@i">Edit</a>
                        <button type="submit" form="remove" name="id" value="@i" class="btn btn-danger" asp-action="Delete" asp-route-id="@i" onclick="return confirm('Do you really want to delete Widget #@i?');">Delete</button>
                    </td>
                </tr>
            }
            </tbody>
        </table>
        <form id="remove" method="post">
            @Html.HttpMethodOverride(HttpMethod.Delete)
        </form>
    </div>
</div>

Crud/Views/Widgets/New.cshtml
@model Crud.ViewModels.Widgets.CreateViewModel

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Widgets > New</h2>

<form method="post"
      asp-controller="Widgets"
      asp-action="Create">
    
    @await Html.PartialAsync("_Edit", Model)
</form>

Crud/Views/Widgets/Show.cshtml
@model Crud.ViewModels.Widgets.EditViewModel

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Show > Widget @Model.Id</h2>

<a class="btn btn-primary" asp-action="Index">
    Back to Index
</a>

Crud/Views/Widgets/_Edit.cshtml
@model Crud.ViewModels.Widgets.CreateViewModel

<div class="form-group">
    <label asp-for="Name"></label>
    <input type="text" class="form-control" asp-for="Name"/>
</div>

<div class="form-group">
    <label asp-for="Weight"></label>
    <input type="number" class="form-control" asp-for="Weight"/>
</div>

<div class="form-group">
    <label asp-for="Manufacturer"></label>
    <select asp-for="Manufacturer" asp-items="Model.Manufacturers"></select>
</div>

<button class="btn btn-primary" type="submit">
    Save
</button>

Crud/Views/Widgets/_Notifications.cshtml
@model dynamic

@if (ViewBag.Message is {} message)
{
    <div class="alert alert-info alert-dismissible fade show" role="alert">
        <p>@message</p>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}